export const COUNTRIES = [
  "Afghanistan", "Albania", "Algeria", "Angola", "Argentina", "Australia",
  "Austria", "Bangladesh", "Belgium", "Benin", "Bolivia", "Brazil",
  "Burkina Faso", "Cameroon", "Canada", "Chad", "Chile", "China",
  "Colombia", "Congo", "Côte d'Ivoire", "Croatia", "Czech Republic",
  "Denmark", "DR Congo", "Ecuador", "Egypt", "Ethiopia", "Finland",
  "France", "Gabon", "Germany", "Ghana", "Greece", "Guatemala",
  "Guinea", "Haiti", "Honduras", "Hungary", "India", "Indonesia",
  "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan",
  "Jordan", "Kazakhstan", "Kenya", "Libya", "Madagascar", "Malawi",
  "Malaysia", "Mali", "Mexico", "Morocco", "Mozambique", "Myanmar",
  "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Norway",
  "Pakistan", "Panama", "Paraguay", "Peru", "Philippines", "Poland",
  "Portugal", "Romania", "Russia", "Rwanda", "Saudi Arabia", "Senegal",
  "Sierra Leone", "Singapore", "Somalia", "South Africa", "South Korea",
  "South Sudan", "Spain", "Sri Lanka", "Sudan", "Sweden", "Switzerland",
  "Syria", "Tanzania", "Thailand", "Togo", "Tunisia", "Turkey", "Uganda",
  "Ukraine", "United Arab Emirates", "United Kingdom", "United States",
  "Uruguay", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe",
];
